import subprocess
__all__ = ['PKG_CONFIG_LIBS', 'CMAKE_LIBS']

PKG_CONFIG_LIBS = {}
CMAKE_LIBS = {}


def update_pkg_config_libs():
    pcs = subprocess.getoutput('pkg-config --list-all').splitlines(False)
    pcs = list(map(lambda x: x.split(' ', 1)[0], pcs))
    for pc in pcs:
        if not pc: continue
        result = subprocess.getoutput('pkg-config --libs ' + pc)
        for lib in result.split(' '):
            if lib.startswith('-l'):
                lib = lib[2:]
                if not lib: continue
                PKG_CONFIG_LIBS[lib] = pc
                print('pkg-config --libs %s ==> %s' % (pc, lib))


update_pkg_config_libs()


QT5MODULES = (
    "3DAnimation", "3DCore", "3DExtras", "3DInput", "3DLogic", "3DQuick", "3DQuickAnimation",
    "3DQuickExtras", "3DQuickInput", "3DQuickRender", "3DQuickScene2D", "3DRender", "Bluetooth",
    "Charts", "Concurrent", "Contacts", "Core", "DBus", "Designer", "GStreamer", "Gui", "Help",
    "LinguistTools", "Location", "Multimedia", "MultimediaWidgets", "Network", "Nfc", "OpenGL",
    "OpenGLExtensions", "Organizer", "Positioning", "PrintSupport", "Qml", "Quick", "QuickControls2",
    "QuickTest", "QuickWidgets", "Script", "ScriptTools", "Sensors", "SerialPort", "Sql", "Svg",
    "Test", "TextToSpeech", "UiPlugin", "UiTools", "Versit", "VersitOrganizer", "WaylandClient",
    "WaylandCompositor", "WebChannel", "WebEngine", "WebEngineCore", "WebEngineWidgets", "WebKit",
    "WebKitWidgets", "WebSockets", "WebView", "Widgets", "X11Extras", "Xml", "XmlPatterns",
)
for module in QT5MODULES:
    CMAKE_LIBS['Qt5' + module] = ('Qt5', module, 'Qt5::' + module, 'Qt5%s_INCLUDE_DIR' % module)

CMAKE_LIBS.update({
    'z': ('ZLIB', None, 'ZLIB_LIBRARIES', 'ZLIB_INCLUDE_DIR'),
    'lzma': ('LibLZMA', None, 'LIBLZMA_LIBRARIES', 'LIBLZMA_INCLUDE_DIR'),
    'X11': ('X11', None, 'X11_LIBRARIES', 'X11_INCLUDE_DIR'),
    "asound": ("ALSA", None, "ALSA_LIBRARY", "ALSA_INCLUDE_DIR"),
    "armadillo": ("Armadillo", None, "ARMADILLO_LIBRARY", "ARMADILLO_INCLUDE_DIR"),
    "aspell": ("ASPELL", None, "ASPELL_LIBRARIES", "ASPELL_INCLUDE_DIR"),
    "aspell-15": ("ASPELL", None, "ASPELL_LIBRARIES", "ASPELL_INCLUDE_DIR"),
    "libaspell-15": ("ASPELL", None, "ASPELL_LIBRARIES", "ASPELL_INCLUDE_DIR"),
    "libaspell": ("ASPELL", None, "ASPELL_LIBRARIES", "ASPELL_INCLUDE_DIR"),
    "aviplay": ("AVIFile", None, "AVIFILE_AVIPLAY_LIBRARY", "AVIFILE_AVIPLAY_INCLUDE_DIR"),
    "execinfo": ("Backtrace", None, "Backtrace_LIBRARY", "Backtrace_INCLUDE_DIR"),
    "bz2": ("BZip2", None, "BZIP2_LIBRARY_RELEASE", "BZIP2_INCLUDE_DIR"),
    "bzip2": ("BZip2", None, "BZIP2_LIBRARY_RELEASE", "BZIP2_INCLUDE_DIR"),
    "CableTclFacility": ("CABLE", None, "CABLE_TCL_LIBRARY", "CABLE_TCL_INCLUDE_DIR"),
    "Coin": ("Coin3D", None, "COIN3D_LIBRARIES", "COIN3D_INCLUDE_DIR"),
    "rt": ("CUDA", None, "CUDA_rt_LIBRARY", "CUDA_rt_INCLUDE_DIR"),
    "cups": ("Cups", None, "CUPS_LIBRARIES", "CUPS_INCLUDE_DIR"),
    "curl": ("CURL", None, "CURL_LIBRARY", "CURL_INCLUDE_DIR"),
    "curses": ("Curses", None, "CURSES_CURSES_LIBRARY", "CURSES_CURSES_INCLUDE_DIR"),
    "IL": ("DevIL", None, "IL_LIBRARIES", "IL_INCLUDE_DIR"),
    "DEVIL": ("DevIL", None, "IL_LIBRARIES", "IL_INCLUDE_DIR"),
    "ILUT": ("DevIL", None, "ILUT_LIBRARIES", "ILUT_INCLUDE_DIR"),
    "ILU": ("DevIL", None, "ILU_LIBRARIES", "ILU_INCLUDE_DIR"),
    "expat": ("EXPAT", None, "EXPAT_LIBRARY", "EXPAT_INCLUDE_DIR"),
    "libexpat": ("EXPAT", None, "EXPAT_LIBRARY", "EXPAT_INCLUDE_DIR"),
    "fl": ("FLEX", None, "FL_LIBRARY", "FL_INCLUDE_DIR"),
    "fltk2": ("FLTK2", None, "FLTK2_BASE_LIBRARY", "FLTK2_BASE_INCLUDE_DIR"),
    "freetype": ("Freetype", None, "FREETYPE_LIBRARY_RELEASE", "FREETYPE_INCLUDE_DIR"),
    "freetyped": ("Freetype", None, "FREETYPE_LIBRARY_DEBUG", "FREETYPE_INCLUDE_DIR"),
    "GLEW": ("GLEW", None, "GLEW_LIBRARY_RELEASE", "GLEW_INCLUDE_DIR"),
    "glew32": ("GLEW", None, "GLEW_LIBRARY_RELEASE", "GLEW_INCLUDE_DIR"),
    "glew": ("GLEW", None, "GLEW_LIBRARY_RELEASE", "GLEW_INCLUDE_DIR"),
    "glew32s": ("GLEW", None, "GLEW_LIBRARY_RELEASE", "GLEW_INCLUDE_DIR"),
    "glut": ("GLUT", None, "GLUT_glut_LIBRARY", "GLUT_glut_INCLUDE_DIR"),
    "glut32": ("GLUT", None, "GLUT_glut_LIBRARY", "GLUT_glut_INCLUDE_DIR"),
    "freeglut": ("GLUT", None, "GLUT_glut_LIBRARY", "GLUT_glut_INCLUDE_DIR"),
    "GLUT": ("GLUT", None, "GLUT_glut_LIBRARY", "GLUT_glut_INCLUDE_DIR"),
    "gnutls": ("GnuTLS", None, "GNUTLS_LIBRARY", "GNUTLS_INCLUDE_DIR"),
    "libgnutls": ("GnuTLS", None, "GNUTLS_LIBRARY", "GNUTLS_INCLUDE_DIR"),
    "gsl": ("GSL", None, "GSL_LIBRARY", "GSL_INCLUDE_DIR"),
    "gslcblas": ("GSL", None, "GSL_CBLAS_LIBRARY", "GSL_CBLAS_INCLUDE_DIR"),
    "cblas": ("GSL", None, "GSL_CBLAS_LIBRARY", "GSL_CBLAS_INCLUDE_DIR"),
    "gsld": ("GSL", None, "GSL_LIBRARY_DEBUG", "GSL_INCLUDE_DIR"),
    "gsl": ("GSL", None, "GSL_LIBRARY_DEBUG", "GSL_INCLUDE_DIR"),
    "gslcblasd": ("GSL", None, "GSL_CBLAS_LIBRARY_DEBUG", "GSL_CBLAS_INCLUDE_DIR"),
    "cblasd": ("GSL", None, "GSL_CBLAS_LIBRARY_DEBUG", "GSL_CBLAS_INCLUDE_DIR"),
    "gslcblas": ("GSL", None, "GSL_CBLAS_LIBRARY_DEBUG", "GSL_CBLAS_INCLUDE_DIR"),
    "cblas": ("GSL", None, "GSL_CBLAS_LIBRARY_DEBUG", "GSL_CBLAS_INCLUDE_DIR"),
    "gtkgl": ("GTK", None, "GTK_gtkgl_LIBRARY", "GTK_gtkgl_INCLUDE_DIR"),
    "gtk": ("GTK", None, "GTK_gtk_LIBRARY", "GTK_gtk_INCLUDE_DIR"),
    "gtk12": ("GTK", None, "GTK_gtk_LIBRARY", "GTK_gtk_INCLUDE_DIR"),
    "gdk": ("GTK", None, "GTK_gdk_LIBRARY", "GTK_gdk_INCLUDE_DIR"),
    "gdk12": ("GTK", None, "GTK_gdk_LIBRARY", "GTK_gdk_INCLUDE_DIR"),
    "gmodule": ("GTK", None, "GTK_gmodule_LIBRARY", "GTK_gmodule_INCLUDE_DIR"),
    "gmodule12": ("GTK", None, "GTK_gmodule_LIBRARY", "GTK_gmodule_INCLUDE_DIR"),
    "glib": ("GTK", None, "GTK_glib_LIBRARY", "GTK_glib_INCLUDE_DIR"),
    "glib12": ("GTK", None, "GTK_glib_LIBRARY", "GTK_glib_INCLUDE_DIR"),
    "Xi": ("GTK", None, "GTK_Xi_LIBRARY", "GTK_Xi_INCLUDE_DIR"),
    "gthread": ("GTK", None, "GTK_gthread_LIBRARY", "GTK_gthread_INCLUDE_DIR"),
    "gthread12": ("GTK", None, "GTK_gthread_LIBRARY", "GTK_gthread_INCLUDE_DIR"),
    "hspell": ("HSPELL", None, "HSPELL_LIBRARIES", "HSPELL_INCLUDE_DIR"),
    "htmlhelp": ("HTMLHelp", None, "HTML_HELP_LIBRARY", "HTML_HELP_INCLUDE_DIR"),
    "intl": ("Intl", None, "Intl_LIBRARY", "Intl_INCLUDE_DIR"),
    "jasper": ("Jasper", None, "JASPER_LIBRARY_RELEASE", "JASPER_INCLUDE_DIR"),
    "libjasper": ("Jasper", None, "JASPER_LIBRARY_RELEASE", "JASPER_INCLUDE_DIR"),
    "kdecore": ("KDE3", None, "KDE3_KDECORE_LIBRARY", "KDE3_KDECORE_INCLUDE_DIR"),
    "archive": ("LibArchive", None, "LibArchive_LIBRARY", "LibArchive_INCLUDE_DIR"),
    "libarchive": ("LibArchive", None, "LibArchive_LIBRARY", "LibArchive_INCLUDE_DIR"),
    "lzma": ("LibLZMA", None, "LIBLZMA_LIBRARY", "LIBLZMA_INCLUDE_DIR"),
    "xml2": ("LibXml2", None, "LIBXML2_LIBRARY", "LIBXML2_INCLUDE_DIR"),
    "libxml2": ("LibXml2", None, "LIBXML2_LIBRARY", "LIBXML2_INCLUDE_DIR"),
    "xslt": ("LibXslt", None, "LIBXSLT_LIBRARIES", "LIBXSLT_INCLUDE_DIR"),
    "libxslt": ("LibXslt", None, "LIBXSLT_LIBRARIES", "LIBXSLT_INCLUDE_DIR"),
    "exslt": ("LibXslt", None, "LIBXSLT_EXSLT_LIBRARY", "LIBXSLT_EXSLT_INCLUDE_DIR"),
    "libexslt": ("LibXslt", None, "LIBXSLT_EXSLT_LIBRARY", "LIBXSLT_EXSLT_INCLUDE_DIR"),
    "lttng-ust": ("LTTngUST", None, "LTTNGUST_LIBRARIES", "LTTNGUST_INCLUDE_DIR"),
    "lua50": ("Lua50", None, "LUA_LIBRARY_lua", "LUA_INCLUDE_DIR"),
    "lua5.0": ("Lua50", None, "LUA_LIBRARY_lua", "LUA_INCLUDE_DIR"),
    "lua-5.0": ("Lua50", None, "LUA_LIBRARY_lua", "LUA_INCLUDE_DIR"),
    "lua5": ("Lua50", None, "LUA_LIBRARY_lua", "LUA_INCLUDE_DIR"),
    "lua": ("Lua50", None, "LUA_LIBRARY_lua", "LUA_INCLUDE_DIR"),
    "lualib50": ("Lua50", None, "LUA_LIBRARY_lualib", "LUA_INCLUDE_DIR"),
    "lualib5.0": ("Lua50", None, "LUA_LIBRARY_lualib", "LUA_INCLUDE_DIR"),
    "lualib5": ("Lua50", None, "LUA_LIBRARY_lualib", "LUA_INCLUDE_DIR"),
    "lualib": ("Lua50", None, "LUA_LIBRARY_lualib", "LUA_INCLUDE_DIR"),
    "lua51": ("Lua51", None, "LUA_LIBRARY", "LUA_INCLUDE_DIR"),
    "lua5.1": ("Lua51", None, "LUA_LIBRARY", "LUA_INCLUDE_DIR"),
    "lua-5.1": ("Lua51", None, "LUA_LIBRARY", "LUA_INCLUDE_DIR"),
    "lua": ("Lua51", None, "LUA_LIBRARY", "LUA_INCLUDE_DIR"),
    "Xm": ("Motif", None, "MOTIF_LIBRARIES", "MOTIF_INCLUDE_DIR"),
    "mpeg2": ("MPEG2", None, "MPEG2_mpeg2_LIBRARY", "MPEG2_mpeg2_INCLUDE_DIR"),
    "mpeg2": ("MPEG", None, "MPEG_mpeg2_LIBRARY", "MPEG_mpeg2_INCLUDE_DIR"),
    "msmpi": ("MPI", None, "MPI_msmpi_LIBRARY", "MPI_msmpi_INCLUDE_DIR"),
    "msmpif": ("MPI", None, "MPI_msmpif_LIBRARY", "MPI_msmpif_INCLUDE_DIR"),
    "mpi": ("MPI", None, "MPI_mpi_LIBRARY", "MPI_mpi_INCLUDE_DIR"),
    "OpenAL": ("OpenAL", None, "OPENAL_LIBRARY", "OPENAL_INCLUDE_DIR"),
    "al": ("OpenAL", None, "OPENAL_LIBRARY", "OPENAL_INCLUDE_DIR"),
    "openal": ("OpenAL", None, "OPENAL_LIBRARY", "OPENAL_INCLUDE_DIR"),
    "OpenAL32": ("OpenAL", None, "OPENAL_LIBRARY", "OPENAL_INCLUDE_DIR"),
    "OpenCL": ("OpenCL", None, "OpenCL_LIBRARY", "OpenCL_INCLUDE_DIR"),
    "OpenCL": ("OpenCL", None, "OpenCL_LIBRARY", "OpenCL_INCLUDE_DIR"),
    "OpenCL": ("OpenCL", None, "OpenCL_LIBRARY", "OpenCL_INCLUDE_DIR"),
    "opengl32": ("OpenGL", None, "OPENGL_gl_LIBRARY", "OPENGL_gl_INCLUDE_DIR"),
    "openmp": ("OpenMP", None, "OpenMP_LIBRARY", "OpenMP_INCLUDE_DIR"),
    "libiomp5md": ("OpenMP", None, "OpenMP_libiomp5md_LIBRARY", "OpenMP_libiomp5md_INCLUDE_DIR"),
    "ssl": ("OpenSSL", None, "OPENSSL_SSL_LIBRARY", "OPENSSL_SSL_INCLUDE_DIR"),
    "crypto": ("OpenSSL", None, "OPENSSL_CRYPTO_LIBRARY", "OPENSSL_CRYPTO_INCLUDE_DIR"),
    "OpenThreads": ("OpenThreads", None, "OPENTHREADS_LIBRARY", "OPENTHREADS_INCLUDE_DIR"),
    "OpenThreadsWin32": ("OpenThreads", None, "OPENTHREADS_LIBRARY", "OPENTHREADS_INCLUDE_DIR"),
    "OpenThreadsd": ("OpenThreads", None, "OPENTHREADS_LIBRARY_DEBUG", "OPENTHREADS_INCLUDE_DIR"),
    "OpenThreadsWin32d": ("OpenThreads", None, "OPENTHREADS_LIBRARY_DEBUG", "OPENTHREADS_INCLUDE_DIR"),
    "physfs": ("PhysFS", None, "PHYSFS_LIBRARY", "PHYSFS_INCLUDE_DIR"),
    "Producer": ("Producer", None, "PRODUCER_LIBRARY", "PRODUCER_INCLUDE_DIR"),
    "python_d": ("PythonLibs", None, "PYTHON_DEBUG_LIBRARY", "PYTHON_DEBUG_INCLUDE_DIR"),
    "python": ("PythonLibs", None, "PYTHON_DEBUG_LIBRARY", "PYTHON_DEBUG_INCLUDE_DIR"),
    "python2": ("PythonLibs", None, "PYTHON_LIBRARY", "PYTHON_INCLUDE_DIR"),
    "python3": ("PythonLibs", None, "PYTHON_LIBRARY", "PYTHON_INCLUDE_DIR"),
    "qt-mt": ("Qt3", None, "QT_QT_LIBRARY", "QT_QT_INCLUDE_DIR"),
    "qt-mtnc": ("Qt3", None, "QT_QT_LIBRARY", "QT_QT_INCLUDE_DIR"),
    "qt": ("Qt3", None, "QT_QT_LIBRARY", "QT_QT_INCLUDE_DIR"),
    "qt-": ("Qt3", None, "QT_QT_LIBRARY", "QT_QT_INCLUDE_DIR"),
    "qt-edu": ("Qt3", None, "QT_QT_LIBRARY", "QT_QT_INCLUDE_DIR"),
    "qassistantclient": ("Qt3", None, "QT_QASSISTANTCLIENT_LIBRARY", "QT_QASSISTANTCLIENT_INCLUDE_DIR"),
    "qtmain": ("Qt3", None, "QT_QTMAIN_LIBRARY", "QT_QTMAIN_INCLUDE_DIR"),
    "QtCore": ("Qt4", None, "QT_QTCORE_LIBRARY_RELEASE", "QT_QTCORE_INCLUDE_DIR"),
    "QtCore4": ("Qt4", None, "QT_QTCORE_LIBRARY_RELEASE", "QT_QTCORE_INCLUDE_DIR"),
    "QtCore_debug": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtCored": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtCored4": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtCore": ("Qt4", None, "QT_QTCORE_LIBRARY_RELEASE", "QT_QTCORE_INCLUDE_DIR"),
    "QtCore4": ("Qt4", None, "QT_QTCORE_LIBRARY_RELEASE", "QT_QTCORE_INCLUDE_DIR"),
    "QtCore_debug": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtCored": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtCored4": ("Qt4", None, "QT_QTCORE_LIBRARY_DEBUG", "QT_QTCORE_INCLUDE_DIR"),
    "QtUiTools": ("Qt4", None, "QT_QTUITOOLS_LIBRARY_RELEASE", "QT_QTUITOOLS_INCLUDE_DIR"),
    "QuickTime": ("QuickTime", None, "QUICKTIME_LIBRARY", "QUICKTIME_INCLUDE_DIR"),
    "RTI": ("RTI", None, "RTI_LIBRARY", "RTI_INCLUDE_DIR"),
    "RTI-NG": ("RTI", None, "RTI_LIBRARY", "RTI_INCLUDE_DIR"),
    "FedTime": ("RTI", None, "RTI_FEDTIME_LIBRARY", "RTI_FEDTIME_INCLUDE_DIR"),
    "SDL": ("SDL", None, "SDL_LIBRARY_TEMP", "SDL_INCLUDE_DIR"),
    "SDL-1.1": ("SDL", None, "SDL_LIBRARY_TEMP", "SDL_INCLUDE_DIR"),
    "SDLmain": ("SDL", None, "SDLMAIN_LIBRARY", "SDLMAIN_INCLUDE_DIR"),
    "SDLmain-1.1": ("SDL", None, "SDLMAIN_LIBRARY", "SDLMAIN_INCLUDE_DIR"),
    "SDL_image": ("SDL_image", None, "SDL_IMAGE_LIBRARY", "SDL_IMAGE_INCLUDE_DIR"),
    "SDL_mixer": ("SDL_mixer", None, "SDL_MIXER_LIBRARY", "SDL_MIXER_INCLUDE_DIR"),
    "SDL_net": ("SDL_net", None, "SDL_NET_LIBRARY", "SDL_NET_INCLUDE_DIR"),
    "SDL_sound": ("SDL_sound", None, "SDL_SOUND_LIBRARY", "SDL_SOUND_INCLUDE_DIR"),
    "libmikmod-coreaudio": ("SDL_sound", None, "MIKMOD_LIBRARY", "MIKMOD_INCLUDE_DIR"),
    "mikmod": ("SDL_sound", None, "MIKMOD_LIBRARY", "MIKMOD_INCLUDE_DIR"),
    "modplug": ("SDL_sound", None, "MODPLUG_LIBRARY", "MODPLUG_INCLUDE_DIR"),
    "vorbis": ("SDL_sound", None, "VORBIS_LIBRARY", "VORBIS_INCLUDE_DIR"),
    "Vorbis": ("SDL_sound", None, "VORBIS_LIBRARY", "VORBIS_INCLUDE_DIR"),
    "VORBIS": ("SDL_sound", None, "VORBIS_LIBRARY", "VORBIS_INCLUDE_DIR"),
    "ogg": ("SDL_sound", None, "OGG_LIBRARY", "OGG_INCLUDE_DIR"),
    "Ogg": ("SDL_sound", None, "OGG_LIBRARY", "OGG_INCLUDE_DIR"),
    "OGG": ("SDL_sound", None, "OGG_LIBRARY", "OGG_INCLUDE_DIR"),
    "smpeg": ("SDL_sound", None, "SMPEG_LIBRARY", "SMPEG_INCLUDE_DIR"),
    "SMPEG": ("SDL_sound", None, "SMPEG_LIBRARY", "SMPEG_INCLUDE_DIR"),
    "Smpeg": ("SDL_sound", None, "SMPEG_LIBRARY", "SMPEG_INCLUDE_DIR"),
    "SMpeg": ("SDL_sound", None, "SMPEG_LIBRARY", "SMPEG_INCLUDE_DIR"),
    "flac": ("SDL_sound", None, "FLAC_LIBRARY", "FLAC_INCLUDE_DIR"),
    "FLAC": ("SDL_sound", None, "FLAC_LIBRARY", "FLAC_INCLUDE_DIR"),
    "speex": ("SDL_sound", None, "SPEEX_LIBRARY", "SPEEX_INCLUDE_DIR"),
    "SPEEX": ("SDL_sound", None, "SPEEX_LIBRARY", "SPEEX_INCLUDE_DIR"),
    "SDL_ttf": ("SDL_ttf", None, "SDL_TTF_LIBRARY", "SDL_TTF_INCLUDE_DIR"),
    "tcl": ("TCL", None, "TCL_LIBRARY", "TCL_INCLUDE_DIR"),
    "tk": ("TCL", None, "TK_LIBRARY", "TK_INCLUDE_DIR"),
    "tclstub": ("TclStub", None, "TCL_STUB_LIBRARY", "TCL_STUB_INCLUDE_DIR"),
    "tkstub": ("TclStub", None, "TK_STUB_LIBRARY", "TK_STUB_INCLUDE_DIR"),
    "ttkstub": ("TclStub", None, "TTK_STUB_LIBRARY", "TTK_STUB_INCLUDE_DIR"),
    "vulkan-1": ("Vulkan", None, "Vulkan_LIBRARY", "Vulkan_INCLUDE_DIR"),
    "vulkan-1": ("Vulkan", None, "Vulkan_LIBRARY", "Vulkan_INCLUDE_DIR"),
    "vulkan": ("Vulkan", None, "Vulkan_LIBRARY", "Vulkan_INCLUDE_DIR"),
    "wx": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxmsw": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxmsw26": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxmswd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxmsw26d": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxmsw26": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw262": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw24": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw242": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw241": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw240": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wx23_2": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wx22_9": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw26d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmsw262d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmsw24d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmsw241d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmsw240d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wx23_2d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wx22_9d": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wx_gl": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_GL", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxmsw_gl": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_GL", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxmsw26_gl": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_GL", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxd_gl": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_GL", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxmswd_gl": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_GL", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxmsw26d_gl": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_GL", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxpngd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_PNG", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxpng": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_PNG", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxtiffd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_TIFF", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxtiff": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_TIFF", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxjpegd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_JPEG", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxjpgd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_JPEG", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxjpeg": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_JPEG", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxjpg": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_JPEG", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxzlibd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_ZLIB", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxzlib": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_ZLIB", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wxregexd": ("wxWindows", None, "WXWINDOWS_STATIC_DEBUG_LIBRARY_REGEX", "WXWINDOWS_STATIC_DEBUG_INCLUDE_DIR"),
    "wxregex": ("wxWindows", None, "WXWINDOWS_STATIC_LIBRARY_REGEX", "WXWINDOWS_STATIC_INCLUDE_DIR"),
    "wx_gl": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY_GL", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw_gl": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY_GL", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxmsw26_gl": ("wxWindows", None, "WXWINDOWS_SHARED_LIBRARY_GL", "WXWINDOWS_SHARED_INCLUDE_DIR"),
    "wxd_gl": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY_GL", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmswd_gl": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY_GL", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "wxmsw26d_gl": ("wxWindows", None, "WXWINDOWS_SHARED_DEBUG_LIBRARY_GL", "WXWINDOWS_SHARED_DEBUG_INCLUDE_DIR"),
    "X11": ("X11", None, "X11_X11_LIB", "X11_X11_INCLUDE_DIR"),
    "Xalan-C": ("XalanC", None, "XalanC_LIBRARY_RELEASE", "XalanC_INCLUDE_DIR"),
    "xalan-c": ("XalanC", None, "XalanC_LIBRARY_RELEASE", "XalanC_INCLUDE_DIR"),
    "Xalan-C_${XalanC_VERSION_MAJOR}": ("XalanC", None, "XalanC_LIBRARY_RELEASE", "XalanC_INCLUDE_DIR"),
    "Xalan-CD": ("XalanC", None, "XalanC_LIBRARY_DEBUG", "XalanC_INCLUDE_DIR"),
    "xalan-cd": ("XalanC", None, "XalanC_LIBRARY_DEBUG", "XalanC_INCLUDE_DIR"),
    "Xalan-C_D": ("XalanC", None, "XalanC_LIBRARY_DEBUG", "XalanC_INCLUDE_DIR"),
    "XCTest": ("XCTest", None, "XCTest_LIBRARY", "XCTest_INCLUDE_DIR"),
    "xerces-c": ("XercesC", None, "XercesC_LIBRARY_RELEASE", "XercesC_INCLUDE_DIR"),
    "xerces-c_3": ("XercesC", None, "XercesC_LIBRARY_RELEASE", "XercesC_INCLUDE_DIR"),
})
